export enum QueryKeys {
  USERS = 'users',
  USERS_ME = 'users-me',
  USER_ACTIVATION = 'user-activation',
  USER_COMPANIES = 'user-companies',
  USER_TICKETS = 'user-tickets',
  USER_EVENTS = 'user-events',
  USER_GEOLOCATION = 'user-geolocation',
  EVENTS = 'events',
  EVENT_ATTENDEES = 'event-attendees',
  EVENT_SUBSCRIBERS = 'event-subscribers',
  TICKETS = 'tickets',
  COMPANIES = 'companies',
  COMPANY_EVENTS = 'company-events',
  COMPANY_SUBSCRIBERS = 'company-subscribers',
  COMPANY_NEWS = 'company-news',
  MY_COMPANIES = 'my-companies',
  COMPANY_PROMO_CODES = 'company-promo-codes',
  COMMENTS = 'comments',
  REACTIONS = 'reactions',
  MY_REACTIONS = 'my-reactions',
  NOTIFICATIONS = 'notifications',
  TICKET_VERIFICATION = 'ticket-verification'
}
